### ISSUE TITLE
Does it support HTML5 drag and drop?

### ISSUE THREAD

**Issue by nickolasgregory** [juanparati/MooUpload#1]
Sorry - unsure from a quick look at the demo.

**Comment by juanparati** [comment]
Don't support yet.

First I want add upload chunk support for Flash and when I finish this part I will add drag & drop support.

Do you know some actionscript guru that can help me?

**Comment by nickolasgregory** [comment]
That was quick :)

For AS I know nothing. You could have a look at; 
https://github.com/digitarald/digitarald-fancyupload
or 
https://github.com/moxiecode/plupload

**Comment by juanparati** [comment]
My script use the same Flash uploader that use Fancyupload (Swiff Uploader)

The difference between Fancyupload and my script is that fancy upload only uses Flash upload, and my script use HTML4, HTML5 and Flash. But my script have a very big advantage and is that you can upload a chunk file with HTML5 overriding the server limitation (yes you can upload big files).

About Plupload is a commercial and close system.

**Comment by juanparati** [comment]
Ohhh

Wait I can see the source code Pluopload flash wrapper!!!

Thanks a lot!!!

**Comment by Zweer** [comment]
first of all hi guys ^^

i can suggest a script to take some help for the drag'n'drop implementation: https://github.com/arian/mootools-form-upload

hope it could be usefull!!

**Comment by juanparati** [comment]
I know how to implement and a drag'n'drop implementation but first I want to add Flash chunk upload support.

Anyway thanks for the suggestion!
