### ISSUE TITLE
Uploading chunks causes Access Denided php error

### ISSUE THREAD

**Issue by albanx** [juanparati/MooUpload#12]
Good, work you have done. I was trying this javascript upload method and I notice that some times files are not uploaded correctly, so with firebug I notice that when sending chunks in upload (html5), the server returns access denided error. (I test this on local host, firefox7,windows,wamp). It seems that when sending a chunks some times the request are so fast that the server hasn't still realease the file meanwhile the next chunks arrive for write. Here is what firebug returns:
<br />
<font size='1'><table class='xdebug-error' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Warning: file_put_contents(C:\wamp\www\juanparati-MooUpload-f2fd419\Demo\tmp\gtt6xlit_DELL_SYSTEM-SOFTWARE_A01_R260746.exe) [<a href='function.file-put-contents'>function.file-put-contents</a>]: failed to open stream: Permission denied in C:\wamp\www\juanparati-MooUpload-f2fd419\Source\mooupload.php on line <i>142</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0003</td><td bgcolor='#eeeeec' align='right'>677784</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\wamp\www\juanparati-MooUpload-f2fd419\Demo\upload.php' bgcolor='#eeeeec'>..\upload.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0008</td><td bgcolor='#eeeeec' align='right'>730672</td><td bgcolor='#eeeeec'>Mooupload::upload(  )</td><td title='C:\wamp\www\juanparati-MooUpload-f2fd419\Demo\upload.php' bgcolor='#eeeeec'>..\upload.php<b>:</b>7</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0008</td><td bgcolor='#eeeeec' align='right'>730704</td><td bgcolor='#eeeeec'>Mooupload::HTML5_upload(  )</td><td title='C:\wamp\www\juanparati-MooUpload-f2fd419\Source\mooupload.php' bgcolor='#eeeeec'>..\mooupload.php<b>:</b>175</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.0011</td><td bgcolor='#eeeeec' align='right'>836968</td><td bgcolor='#eeeeec'><a href='http://www.php.net/file_put_contents' target='_new'>file_put_contents</a>
(  )</td><td title='C:\wamp\www\juanparati-MooUpload-f2fd419\Source\mooupload.php' bgcolor='#eeeeec'>..\mooupload.php<b>:</b>142</td></tr>
</table></font>
{"id":"gtt6xlit","name":"DELL_SYSTEM-SOFTWARE_A01_R260746.exe","size":"102400","error":7,"finish":false,"upload_name":"gtt6xlit_DELL_SYSTEM-SOFTWARE_A01_R260746.exe"}

Any Idea how to avoid this error?

**Comment by juanparati** [comment]
I am using a WAMP system like you, and I never had this problem.

It seens that you have configured a very low blocksize (Not recommended for fast connections), or an application like antivirus, malware (a virus trying to infect the file), hypervisor (lock up the file meanwhile is waiting for confirmation) or maintenance application (reading and writing metadata) is locking the access to the uploaded files.

**Comment by juanparati** [comment]
Can you send me your phpinfo()?

**Comment by albanx** [comment]
some of php_info, but I have not changed any of them since I installed wamp:
max_execution_time  300 300
max_file_uploads    20  20
max_input_nesting_level 64  64
max_input_time  600 600
memory_limit    128M    128M
open_basedir    no value    no value
output_buffering    1   1
output_handler  no value    no value
post_max_size   80M 80M

The first comment you make, make me worried. but i think it's none of the above because the problem happens randomly only on a few chunks: When trasmiting for example 15 chunks the problem happens only on chunk 11 or chunk 5, the other chunks are written successfully on the file. I founded a workround for avoid the problem using this loop:
<code>
            $file_part=file_get_contents('php://input');//REMEMBER php::/input can be read only one in the same script execution, so better mem it in a var
            while(@file_put_contents($remotePath.$file_name, $file_part,$flag)===FALSE)//strange bug
            {
                usleep(50);
            }
</code>

**Comment by juanparati** [comment]
Is a strange bug! 

Thanks for the solutions.

Anyway I can't introduce this patch, because override file_put_contents errors is not a good idea. Specially if you are executing PHP in Safe Mode or if you don't give write permissions to the temp directory.

If you upload MooUpload to a remote web server, you could not use this patch because the network upload will be about 100000 more slow that when you try to upload files to 127.0.0.1, so your server (even if is a very slow machine) could be open, write and close the upload file without problems.

One question more, what windows version and file system are you using?

**Comment by albanx** [comment]
Yes, I know that's not a good solution, but also I think it happens only on localhost connections for speed. I am using Win7, with Microsoft Security Essential antivirus, and NTFS file system under limited user (but wamp running in admin user).

**Comment by danielbidala** [comment]
Dear albanx

I use mootools uploder and run into this problem on a LAN project. Can you help me how to apply your patch mentioned in the above post?

Thanks in advance.
