### ISSUE TITLE
Mooupload Class - getallheader

### ISSUE THREAD

**Issue by minhna** [juanparati/MooUpload#13]
Hi,
Firstly, thank you for created a awesome upload tool.
Then I found a minor issue. You used getallheaders() function to read header from request. But you know, currently almost shared webserver use PHP-CGI version 5.2.x and that function doesn't work. The getallheaders function only available in php module mode (almost version of PHP).

I had to modify like this bellow:
    if (function_exists('getallheaders')) {
        $headers    = getallheaders();
    }
    else {
        $headers = array();
        $headers['X-File-Id']       = $_SERVER['HTTP_X_FILE_ID'];
        $headers['X-File-Name']     = $_SERVER['HTTP_X_FILE_NAME'];
        $headers['Content-Length']  = $_SERVER['CONTENT_LENGTH'];
        $headers['X-File-Resume']   = $_SERVER['HTTP_X_FILE_RESUME'];
        $headers['X-File-Size']     = $_SERVER['HTTP_X_FILE_SIZE'];
    }

It works for me.
Thank you.
Minh

**Comment by juanparati** [comment]
Thanks Minh!

Siteroller (other github user) has reimplemented a getallheaders for PHP-CGI, but I replaced this piece of code for other based in your code for security and scalability questions.

I have update the code, Can you tested this new code in your PHP-CGI webserver?

**Comment by minhna** [comment]
It works like a charm. Thank you.
