### ISSUE TITLE
Flash Upload Large Files

### ISSUE THREAD

**Issue by PeteAUK** [juanparati/MooUpload#18]
Flash uploader doesn't appear to upload files larger than 2Mb (tried a 3Mb & 5Mb).  Max upload on the server is 30Mb.  This is using the flash method in either IE or FF

**Comment by juanparati** [comment]
Have you check in your phpinfo() if "post_max_size" and "upload_max_filesize" is highter than 2Mb?

**Comment by PeteAUK** [comment]
Hi,

Grrr, thanks for that.  It was setup correctly under IIS but not the php.ini :(  I forgot that the ini file take precedence over the IIS setting
