### ISSUE TITLE
Send parameters

### ISSUE THREAD

**Issue by YuccaOne** [juanparati/MooUpload#19]
Hi,

I would like to send some parameters to php file (upload.php in your example), like user id and directory destination ; how can I do that ?

Thanks

**Comment by juanparati** [comment]
You can send this parameters using the $_GET parameters in the uploaded URL.

Example:

```
 var myUpload = new MooUpload('filecontrol', {
      action: 'upload.php?user_id=123&destination=images'
});
```

You can get this parameters from PHP using the $_GET global var..
