### ISSUE TITLE
Flash mode doesn't return anything in callback

### ISSUE THREAD

**Issue by oskarkrawczyk** [juanparati/MooUpload#21]
In flash mode, the onFinishUpload should respond with two arguments, the second being the actual response that comes from the server. Currently this argument is always undefined, wheres in html4/5 modes this returns the correct response.

Any ides what can be the cause of this?

**Comment by juanparati** [comment]
onFinishUpload do not return any argument.  This event is only is fired when the upload is finish.

Are you talking about "onFileUpload" ??

**Comment by oskarkrawczyk** [comment]
Indeed. After poking around with DropZone, I noticed you've fixed most MooUpload bugs when it comes to firing events.

All seems to work fine (apart from the other bug I've posted).

[UPDATE]

Damn, wrong repo, again...

Yes, `onFileUpload` doesn't pass any arguments.

**Comment by juanparati** [comment]
Fixed!  

Download the last version!

Now you will the get the parameters on FileComplete using the Flash method.

Please check out the new version and close this issue if it work fine.

Thank you for report this bug!

**Comment by oskarkrawczyk** [comment]
Works fine.

Thanks for the patch!
