### ISSUE TITLE
`accept` and `multiple` options do not work

### ISSUE THREAD

**Issue by lorenzos** [juanparati/MooUpload#24]
The `accept` and `multiple` options do not work (at least, they do not for HTML5 method).

With the following code, I was able to upload any number of files of any type, not only one single PDF:

```
    new MooUpload('uploadcontrol', {
        action: 'upload.php',
        accept: 'application/pdf',
        multiple: false,
        maxuploadspertime: 1
    });
```

**Comment by juanparati** [comment]
Some web browsers like Firefox have a different and non-standard HTML5 file filter implementation. So for example with firefox works partial filters like "image/_" but not "image/png". However in Chrome "image/png" and "image/_" and "application/pdf" works.

**Comment by lorenzos** [comment]
Ok, I solved checking it on the PHP-side of the uploader. Thank you.

**Comment by juanparati** [comment]
Lorenzo, I have just reported to Mozilla about the wrong "Accepts" implementation.

Bug report: [773985](https://bugzilla.mozilla.org/show_bug.cgi?id=773985#)

**Comment by juanparati** [comment]
I can see that Mozilla guys have prepared a patch for the 15.x Release

See the bug report: [565274](https://bugzilla.mozilla.org/show_bug.cgi?id=565274)

So, this means that MooUpload will works as expected

**Comment by lorenzos** [comment]
Really cool. Thank you.
