### ISSUE TITLE
new Event(e).stop(); not compatible with moo 1.4.5

### ISSUE THREAD

**Issue by hamburger123456** [juanparati/MooUpload#26]
can you edit line257
new Event(e).stop();
is not compatible with moo 1.4.5
thanks

**Comment by juanparati** [comment]
I think that MooUpload was updated like 2 months ago. Have you checked the last version?

**Comment by hamburger123456** [comment]
Ok. I have it from moo-fork some hours ago.
But I see there is a newer version here.

**Comment by hamburger123456** [comment]
it works fine.
chapeau  juanparati
