### ISSUE TITLE
IE Errors

### ISSUE THREAD

**Issue by PeteAUK** [juanparati/MooUpload#3]
IE 8 generates a number of errors (including in the demo) when flashElement.getParent is called (line 749).  This appears to be peculiar only to IE and Chrome & Firefox work without problem.

**Comment by juanparati** [comment]
Hi Pete!

I know about this issue. I am trying to replace the flash load detection with other that works in Internet Explorer.

Meanwhile I have commented the flash load detection code. So you can upload the code updated from the repository

Thanks to your report I have found some minor bugs.

**Comment by PeteAUK** [comment]
Fantastic, much appreciated.
