### ISSUE TITLE
slice is not defined

### ISSUE THREAD

**Issue by siteroller** [juanparati/MooUpload#9]
Error thrown on Demo page.
Uploading hangs at 50%.

Safari 5.1 on Mac Snow Leopard

TypeError: 'undefined' is not a function (evaluating 'file.slice(start, total)')

Console.log shows that there is no slice or webkitSlice for file.

**Comment by siteroller** [comment]
Tested in Firefox 7.0.1 and it works correctly.

**Comment by juanparati** [comment]
I tested in Chrome (That use webkit!) and also works correctly. 

Hmmm I think that I going to borrow the MacBook of my wife and see what happen with Safari

**Comment by siteroller** [comment]
According to [Mozilla](https://developer.mozilla.org/en/DOM/BlobBuilder) blobBuilder is supported by Chrome, but Safari's support is only in trunk.  
It makes some sense that slice inherits from blob, so that might be the direction - I haven't found the relevant page on Surfin Safari.

**Comment by juanparati** [comment]
Yes, you are right!

I checked out http://beta.html5test.com/ with Safari, and I can could see how FileReader API is not supported.

More documentation:
http://www.html5rocks.com/en/tutorials/file/dndfiles/

So I have decided to edit the detection method.

**Comment by siteroller** [comment]
Have you pushed those changes to the detection method?

**Comment by juanparati** [comment]
Yes in 0.99
